### PR TITLE
Feature: add custom CSS options

### LINKED ISSUE #2: CSS modifications?
👋 Hello @martinctc! This is a very cool package, thank you for developing and sharing it 👏 

I don't have the "Segoe UI" font family and the example html output is rendering with Times New Roman (please see screenshot below) 😢 

It'd be really helpful if we could pick our own fonts and style other elements of the doc. Would it be possible to modify the package so that the [`style.css`](https://github.com/martinctc/parallaxr/blob/main/inst/style.css) sheet is easily accessible somewhere for users to make their own changes?

image

### LINKED ISSUE #5: Feature: Customize image and widget sizes
Thank you for this awesome package. I have a question about modifying the image and widget sizes. Since parallaxr parses .md files only, is there any documentation of all the header options of .md files? I have never used .md before (only .Rmd).

Specifically, is it possible to change the size of the images on left and right in .md? I want to make my widget larger than the image. In some cases, I want to put just the image taking all the space. Is that possible?

Thank you for your time.

### PR DESCRIPTION
**Pull request by martinctc**
# Summary
This branch adds custom CSS options and alterantive options to `Segoe UI`.

# Changes
The changes made in this PR are:
1. Added an argument in `generate_scroll_doc()` to provide custom CSS.
1. Added a function `default_css()` to return the default CSS file, so the user can edit and save this to be used in `generate_scroll_doc()`.
1. Added alternative options to `Segoe UI`.
1. Updated example HTML file.

# Check
- [x] All R CMD checks pass.
...

#  Note
This fixes #2 and helps address an issue in #5 (not resolved).

### CODE REVIEW

**Comment by martinctc** [comment]
@spcanelon Please comment if the code works for you, or if you have any suggestions! Feel free to make code changes too if you are happy to.

**Comment by martinctc** [comment]
@spcanelon no rush, but let me know if you've had any issues running the code! If there are no immediate errors or bugs but you think there is potential scope for future enhancements, we can maybe merge this change and then create a new pull request in the future. Thanks!

**Comment by spcanelon** [comment]
Hi @martinctc! Thanks for the friendly nudge. I haven't tried it yet but will be happy to try it today 😄 
Re: future enhancements -- something I'd love to do, but don't yet know how, is help convert this into an R markdown template. Maybe something to think about for the future?

**Comment by spcanelon** [comment]
Hi @martinctc! I finally had a chance to try this out.

When I try the `default_css()` code I get the below screenshot as an output, is that what you intended?

In this format I'm afraid it's not very user-friendly. I copied and pasted this raw output into a new `.css` file hoping there would be an option in the **Code** menu dropdown to format it but there wasn't one. Formatting it by hand would take some time. Am I missing something? 🤔 

image

In the below section of the code, instead of using `readLines()` and `paste()` would it be possible to do something like save a copy of the `style.css` file somewhere in the home directory?
```
default_css <- function(){

  readLines(con = system.file("style.css", package = "parallaxr"), warn = FALSE) %>%
    paste(collapse = " ")

}
```

**Comment by martinctc** [comment]
> Hi @martinctc! I finally had a chance to try this out.
> 
> When I try the `default_css()` code I get the below screenshot as an output, is that what you intended?
> 
> In this format I'm afraid it's not very user-friendly. I copied and pasted this raw output into a new `.css` file hoping there would be an option in the **Code** menu dropdown to format it but there wasn't one. Formatting it by hand would take some time. Am I missing something? 🤔
> 
> image
> 
> In the below section of the code, instead of using `readLines()` and `paste()` would it be possible to do something like save a copy of the `style.css` file somewhere in the home directory?
> 
> ```
> default_css <- function(){
> 
>   readLines(con = system.file("style.css", package = "parallaxr"), warn = FALSE) %>%
>     paste(collapse = " ")
> 
> }
> ```

Hi @spcanelon - VS code has a method for formatting CSS code:
https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&cad=rja&uact=8&ved=2ahUKEwie3cb4-MPtAhUJV8AKHQu_CKkQFjABegQIBBAC&url=https%3A%2F%2Fstackoverflow.com%2Fquestions%2F37739375%2Fvisual-studio-code-css-indentation-and-formatting%23%3A~%3Atext%3DYes%252C%2520try%2520installing%2520vscode%252Dcss%2Csame%2520Alt%2520%252B%2520Shift%2520%252B%2520F%2520.%26text%3Dpress%2520F1%2520or%2520ctrl%252Bshift%2Cp%2520and%2520then%2520enter%2520beautify%2520..&usg=AOvVaw3PqkHJP3o9eMOsmCgcWPEm

I agree it'll be good to return a version that is well-formatted to the user for editing though, as it makes everything easier. What I'll do is to start a new issue so we can at least make this current feature (custom CSS) available first to other users.

**Comment by spcanelon** [comment]
Hi @martinctc, thanks for that tip about VS Code, that's a great feature! I've heard now from a few people that VS Code is more accessible than RStudio in a lot of ways and I've been meaning to give it a try for myself 👍

Thanks for starting a new issue about the CSS output. I don't have capacity at the moment to help figure out a solution but I'll make a point to check back in January 🙂

**Comment by martinctc** [comment]
@spcanelon This is now fixed and merged into the main branch! It should now return a pretty output, with an option to save the CSS file as a file to your directory. If this still doesn't work please start a new issue, but I've tested it so should be fine :)

**Pull request merged**
